apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pq8etnzak-go 
  janus-idp.io/tekton: pq8etnzak-go
  backstage.io/kubernetes-id: pq8etnzak-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pq8etnzak-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  